export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_ABILITY_INFO = 'GET_ABILITY_INFO';
export const START_FETCH_ABILITY = 'START_FETCH_ABILITY';
export const GET_SEARCH_POKEMONS = 'GET_SEARCH_POKEMONS';


